/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Coche(private var _marca: String = "Ford", private var _modelo: Int = 2020) {
    var marca: String
        get() = _marca
        set(value) { _marca = value }

    var modelo: Int
        get() = _modelo
        set(value) { _modelo = value }
}

// 1) Interfaz
interface Perimetrable {
    fun calcularPerimetro(): Double
}

// 2) Circulo implementa Perimetrable
class Circulo(private val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double {
        return 2 * Math.PI * radio
    }
}

// 3) Rectangulo implementa Perimetrable
class Rectangulo(private val ancho: Double, private val alto: Double) : Perimetrable {
    override fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}

// 4) Mostrar perímetros de una lista de figuras
fun mostrarPerimetros() {
    val figuras: List<Perimetrable> = listOf(
        Circulo(5.0),
        Rectangulo(4.0, 6.0)
    )
    for (figura in figuras) {
        println("Perímetro: ${figura.calcularPerimetro()}")
    }
}

fun main() {
    val coche = Coche("Chevrolet", 2025)
    println("Marca ${coche.marca}")
    println("Modelo ${coche.modelo}")

    mostrarPerimetros()
}

    // Escribir una interface perimetrable con un metodo calcularPerimetro()
    // Escribir una clase Rectangulo que implemente la interface Perimetrable
    // Escribir una clase Circulo que implemente la interface Perimetrable
    // Crear una lista con un objeto de cada clase y mostrar el perimetro de cada uno